# Generated by Django 3.2.25 on 2024-12-10 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('Courses for schools/education', 'Courses for schools/education'), ('Pricing Inquiry', 'Pricing Inquiry'), ('Business Inquiry', 'Business Inquiry'), ('Trouble using the site', 'Trouble using the site'), ('Trouble accessing my course', 'Trouble accessing my course'), ('Account Issues', 'Account Issues'), ('Other', 'Other')], max_length=254)),
                ('message', models.TextField(max_length=1024)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Contact Requests',
            },
        ),
    ]
