# Generated by Django 3.2.25 on 2024-12-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('1-Beginner', '1-Beginnner'), ('2-Intermediate', '2-Intermediate'), ('3-Advanced', '3-Advanced')], max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='level_display_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
